[package]
authors = ["ocbwoy3"]
edition = "2021"
name = "native-luau-compiler-napi"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.12.1", features = ["luau"] }
napi = "3.12.4"
napi-derive = "3.6.5"

[build-dependencies]
napi-build = "2.4.2"

[profile.release]
lto = true
strip = "symbols"
