/* auto-generated by NAPI-RS */
/* eslint-disable */

/** Compiles the given Luau code into bytecode or throws an error */
export declare function compileLuau(source: string, options?: CompileOptions | undefined | null): Buffer

/** Compile options object passed from JS */
export interface CompileOptions {
  /** 0..=2 (default 1) */
  optimizationLevel?: number
  /** 0..=2 (default 0) */
  coverageLevel?: number
  /** 0..=2 (default 1) */
  debugLevel?: number
}
